module.exports = class Data1675140241343 {
    name = 'Data1675140241343'

    async up(db) {
        await db.query(`CREATE TABLE "global_state" ("id" character varying NOT NULL, "height" integer NOT NULL, "total_value" numeric NOT NULL, "average_block_time_updated_height" integer NOT NULL, "average_block_time_updated_time" TIMESTAMP WITH TIME ZONE NOT NULL, "average_block_time" integer NOT NULL, "average_apr_multiplier_updated_time" TIMESTAMP WITH TIME ZONE NOT NULL, "average_apr_multiplier" numeric NOT NULL, "idle_worker_shares" numeric NOT NULL, CONSTRAINT "PK_8b4db1150cf49bfd067e2572c74" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "base_pool_whitelist" ("id" character varying NOT NULL, "create_time" TIMESTAMP WITH TIME ZONE NOT NULL, "account_id" character varying, "base_pool_id" character varying, CONSTRAINT "PK_1a86621574257deb7a2b7b4d7d7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_57aaf3859a02333f595bd5bd22" ON "base_pool_whitelist" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_993eea06189ccb1817da97adab" ON "base_pool_whitelist" ("base_pool_id") `)
        await db.query(`CREATE TABLE "nft" ("id" character varying NOT NULL, "cid" integer NOT NULL, "nft_id" integer NOT NULL, "burned" boolean NOT NULL, "mint_time" TIMESTAMP WITH TIME ZONE, "owner_id" character varying, CONSTRAINT "PK_8f46897c58e23b0e7bf6c8e56b0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_83cfd3a290ed70c660f8c9dfe2" ON "nft" ("owner_id") `)
        await db.query(`CREATE TABLE "delegation" ("id" character varying NOT NULL, "value" numeric NOT NULL, "shares" numeric NOT NULL, "withdrawing_value" numeric NOT NULL, "withdrawing_shares" numeric NOT NULL, "withdrawal_start_time" TIMESTAMP WITH TIME ZONE, "account_id" character varying, "base_pool_id" character varying, "delegation_nft_id" character varying NOT NULL, "withdrawal_nft_id" character varying, CONSTRAINT "REL_2d6f29d59b2d5cd7e3034ab857" UNIQUE ("delegation_nft_id"), CONSTRAINT "PK_a2cb6c9b942d68b109131beab44" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_be5a5e334e4fb53a0cab3b0125" ON "delegation" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_4b95628b3ff2b93f23b1f59ae4" ON "delegation" ("base_pool_id") `)
        await db.query(`CREATE UNIQUE INDEX "IDX_2d6f29d59b2d5cd7e3034ab857" ON "delegation" ("delegation_nft_id") `)
        await db.query(`CREATE INDEX "IDX_f7f610da28f4e55602c9def52a" ON "delegation" ("withdrawal_nft_id") `)
        await db.query(`CREATE TABLE "base_pool" ("id" character varying NOT NULL, "pid" numeric NOT NULL, "cid" integer NOT NULL, "kind" character varying(9) NOT NULL, "commission" numeric NOT NULL, "apr_multiplier" numeric NOT NULL, "total_shares" numeric NOT NULL, "total_value" numeric NOT NULL, "share_price" numeric NOT NULL, "free_value" numeric NOT NULL, "releasing_value" numeric NOT NULL, "withdrawing_value" numeric NOT NULL, "withdrawing_shares" numeric NOT NULL, "delegator_count" integer NOT NULL, "whitelist_enabled" boolean NOT NULL, "owner_id" character varying, "account_id" character varying NOT NULL, CONSTRAINT "REL_b17f3b9349da680afa1e2e9805" UNIQUE ("account_id"), CONSTRAINT "PK_eddfb05533fbdd025660778c6a2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e20be4204009ad2ad1d17a125d" ON "base_pool" ("owner_id") `)
        await db.query(`CREATE UNIQUE INDEX "IDX_b17f3b9349da680afa1e2e9805" ON "base_pool" ("account_id") `)
        await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, "identity_display" text, "identity_level" character varying(10), "stake_pool_value" numeric NOT NULL, "stake_pool_nft_count" integer NOT NULL, "stake_pool_avg_apr_multiplier" numeric NOT NULL, "vault_value" numeric NOT NULL, "vault_nft_count" integer NOT NULL, "vault_avg_apr_multiplier" numeric NOT NULL, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "vault" ("id" character varying NOT NULL, "last_share_price_checkpoint" numeric NOT NULL, "claimable_owner_shares" numeric NOT NULL, "base_pool_id" character varying NOT NULL, CONSTRAINT "REL_79f07f6ce7cca2f1ebfc2c0b11" UNIQUE ("base_pool_id"), CONSTRAINT "PK_dd0898234c77f9d97585171ac59" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "IDX_79f07f6ce7cca2f1ebfc2c0b11" ON "vault" ("base_pool_id") `)
        await db.query(`CREATE TABLE "session" ("id" character varying NOT NULL, "is_bound" boolean NOT NULL, "stake" numeric NOT NULL, "state" character varying(18) NOT NULL, "v" numeric NOT NULL, "ve" numeric NOT NULL, "p_init" integer NOT NULL, "p_instant" integer NOT NULL, "total_reward" numeric NOT NULL, "cooling_down_start_time" TIMESTAMP WITH TIME ZONE, "stake_pool_id" character varying, "worker_id" character varying, CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_84c1c253406ae3adb5ba41ff7d" ON "session" ("stake_pool_id") `)
        await db.query(`CREATE INDEX "IDX_30db46e58a0ae3fbc408179de8" ON "session" ("worker_id") `)
        await db.query(`CREATE TABLE "worker" ("id" character varying NOT NULL, "confidence_level" integer NOT NULL, "initial_score" integer, "shares" numeric, "stake_pool_id" character varying, "session_id" character varying, CONSTRAINT "PK_dc8175fa0e34ce7a39e4ec73b94" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_81caea9d964ee3c0338fd44db4" ON "worker" ("stake_pool_id") `)
        await db.query(`CREATE INDEX "IDX_9d35228a135aa08da0b546b58a" ON "worker" ("session_id") `)
        await db.query(`CREATE TABLE "stake_pool" ("id" character varying NOT NULL, "capacity" numeric, "delegable" numeric, "owner_reward" numeric NOT NULL, "worker_count" integer NOT NULL, "idle_worker_count" integer NOT NULL, "idle_worker_shares" numeric NOT NULL, "base_pool_id" character varying NOT NULL, CONSTRAINT "REL_663952452d6814016e857b710b" UNIQUE ("base_pool_id"), CONSTRAINT "PK_646d137a2979aa231fa880711f3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "IDX_663952452d6814016e857b710b" ON "stake_pool" ("base_pool_id") `)
        await db.query(`CREATE TABLE "delegation_value_record" ("id" character varying NOT NULL, "updated_time" TIMESTAMP WITH TIME ZONE NOT NULL, "value" numeric NOT NULL, "account_id" character varying, CONSTRAINT "PK_04d40954ab0809e675a86535d38" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_c437fcb71b7a03f2dd1a99ebc6" ON "delegation_value_record" ("account_id") `)
        await db.query(`CREATE TABLE "reward_record" ("id" character varying NOT NULL, "time" TIMESTAMP WITH TIME ZONE NOT NULL, "value" numeric NOT NULL, CONSTRAINT "PK_14c183bc814ae3c3b24f2595576" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "base_pool_apr_record" ("id" character varying NOT NULL, "updated_time" TIMESTAMP WITH TIME ZONE NOT NULL, "value" numeric NOT NULL, "base_pool_id" character varying, CONSTRAINT "PK_7bec4170d859a827648e0eb8485" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_2ee5286002887363810291f9df" ON "base_pool_apr_record" ("base_pool_id") `)
        await db.query(`ALTER TABLE "base_pool_whitelist" ADD CONSTRAINT "FK_57aaf3859a02333f595bd5bd224" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "base_pool_whitelist" ADD CONSTRAINT "FK_993eea06189ccb1817da97adaba" FOREIGN KEY ("base_pool_id") REFERENCES "base_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_83cfd3a290ed70c660f8c9dfe2c" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation" ADD CONSTRAINT "FK_be5a5e334e4fb53a0cab3b01254" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation" ADD CONSTRAINT "FK_4b95628b3ff2b93f23b1f59ae44" FOREIGN KEY ("base_pool_id") REFERENCES "base_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation" ADD CONSTRAINT "FK_2d6f29d59b2d5cd7e3034ab8574" FOREIGN KEY ("delegation_nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation" ADD CONSTRAINT "FK_f7f610da28f4e55602c9def52a5" FOREIGN KEY ("withdrawal_nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "base_pool" ADD CONSTRAINT "FK_e20be4204009ad2ad1d17a125de" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "base_pool" ADD CONSTRAINT "FK_b17f3b9349da680afa1e2e98055" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "vault" ADD CONSTRAINT "FK_79f07f6ce7cca2f1ebfc2c0b117" FOREIGN KEY ("base_pool_id") REFERENCES "base_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_84c1c253406ae3adb5ba41ff7db" FOREIGN KEY ("stake_pool_id") REFERENCES "stake_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_30db46e58a0ae3fbc408179de88" FOREIGN KEY ("worker_id") REFERENCES "worker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "worker" ADD CONSTRAINT "FK_81caea9d964ee3c0338fd44db4a" FOREIGN KEY ("stake_pool_id") REFERENCES "stake_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "worker" ADD CONSTRAINT "FK_9d35228a135aa08da0b546b58ab" FOREIGN KEY ("session_id") REFERENCES "session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stake_pool" ADD CONSTRAINT "FK_663952452d6814016e857b710b4" FOREIGN KEY ("base_pool_id") REFERENCES "base_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation_value_record" ADD CONSTRAINT "FK_c437fcb71b7a03f2dd1a99ebc67" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "base_pool_apr_record" ADD CONSTRAINT "FK_2ee5286002887363810291f9dfd" FOREIGN KEY ("base_pool_id") REFERENCES "base_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "global_state"`)
        await db.query(`DROP TABLE "base_pool_whitelist"`)
        await db.query(`DROP INDEX "public"."IDX_57aaf3859a02333f595bd5bd22"`)
        await db.query(`DROP INDEX "public"."IDX_993eea06189ccb1817da97adab"`)
        await db.query(`DROP TABLE "nft"`)
        await db.query(`DROP INDEX "public"."IDX_83cfd3a290ed70c660f8c9dfe2"`)
        await db.query(`DROP TABLE "delegation"`)
        await db.query(`DROP INDEX "public"."IDX_be5a5e334e4fb53a0cab3b0125"`)
        await db.query(`DROP INDEX "public"."IDX_4b95628b3ff2b93f23b1f59ae4"`)
        await db.query(`DROP INDEX "public"."IDX_2d6f29d59b2d5cd7e3034ab857"`)
        await db.query(`DROP INDEX "public"."IDX_f7f610da28f4e55602c9def52a"`)
        await db.query(`DROP TABLE "base_pool"`)
        await db.query(`DROP INDEX "public"."IDX_e20be4204009ad2ad1d17a125d"`)
        await db.query(`DROP INDEX "public"."IDX_b17f3b9349da680afa1e2e9805"`)
        await db.query(`DROP TABLE "account"`)
        await db.query(`DROP TABLE "vault"`)
        await db.query(`DROP INDEX "public"."IDX_79f07f6ce7cca2f1ebfc2c0b11"`)
        await db.query(`DROP TABLE "session"`)
        await db.query(`DROP INDEX "public"."IDX_84c1c253406ae3adb5ba41ff7d"`)
        await db.query(`DROP INDEX "public"."IDX_30db46e58a0ae3fbc408179de8"`)
        await db.query(`DROP TABLE "worker"`)
        await db.query(`DROP INDEX "public"."IDX_81caea9d964ee3c0338fd44db4"`)
        await db.query(`DROP INDEX "public"."IDX_9d35228a135aa08da0b546b58a"`)
        await db.query(`DROP TABLE "stake_pool"`)
        await db.query(`DROP INDEX "public"."IDX_663952452d6814016e857b710b"`)
        await db.query(`DROP TABLE "delegation_value_record"`)
        await db.query(`DROP INDEX "public"."IDX_c437fcb71b7a03f2dd1a99ebc6"`)
        await db.query(`DROP TABLE "reward_record"`)
        await db.query(`DROP TABLE "base_pool_apr_record"`)
        await db.query(`DROP INDEX "public"."IDX_2ee5286002887363810291f9df"`)
        await db.query(`ALTER TABLE "base_pool_whitelist" DROP CONSTRAINT "FK_57aaf3859a02333f595bd5bd224"`)
        await db.query(`ALTER TABLE "base_pool_whitelist" DROP CONSTRAINT "FK_993eea06189ccb1817da97adaba"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_83cfd3a290ed70c660f8c9dfe2c"`)
        await db.query(`ALTER TABLE "delegation" DROP CONSTRAINT "FK_be5a5e334e4fb53a0cab3b01254"`)
        await db.query(`ALTER TABLE "delegation" DROP CONSTRAINT "FK_4b95628b3ff2b93f23b1f59ae44"`)
        await db.query(`ALTER TABLE "delegation" DROP CONSTRAINT "FK_2d6f29d59b2d5cd7e3034ab8574"`)
        await db.query(`ALTER TABLE "delegation" DROP CONSTRAINT "FK_f7f610da28f4e55602c9def52a5"`)
        await db.query(`ALTER TABLE "base_pool" DROP CONSTRAINT "FK_e20be4204009ad2ad1d17a125de"`)
        await db.query(`ALTER TABLE "base_pool" DROP CONSTRAINT "FK_b17f3b9349da680afa1e2e98055"`)
        await db.query(`ALTER TABLE "vault" DROP CONSTRAINT "FK_79f07f6ce7cca2f1ebfc2c0b117"`)
        await db.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_84c1c253406ae3adb5ba41ff7db"`)
        await db.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_30db46e58a0ae3fbc408179de88"`)
        await db.query(`ALTER TABLE "worker" DROP CONSTRAINT "FK_81caea9d964ee3c0338fd44db4a"`)
        await db.query(`ALTER TABLE "worker" DROP CONSTRAINT "FK_9d35228a135aa08da0b546b58ab"`)
        await db.query(`ALTER TABLE "stake_pool" DROP CONSTRAINT "FK_663952452d6814016e857b710b4"`)
        await db.query(`ALTER TABLE "delegation_value_record" DROP CONSTRAINT "FK_c437fcb71b7a03f2dd1a99ebc67"`)
        await db.query(`ALTER TABLE "base_pool_apr_record" DROP CONSTRAINT "FK_2ee5286002887363810291f9dfd"`)
    }
}
