module.exports = class Data1708710076811 {
    name = 'Data1708710076811'

    async up(db) {
        await db.query(`CREATE TABLE "global_state" ("id" character varying NOT NULL, "height" integer NOT NULL, "total_value" numeric NOT NULL, "average_block_time_updated_height" integer NOT NULL, "average_block_time_updated_time" TIMESTAMP WITH TIME ZONE NOT NULL, "snapshot_updated_time" TIMESTAMP WITH TIME ZONE NOT NULL, "average_block_time" integer NOT NULL, "average_apr_multiplier" numeric NOT NULL, "average_apr" numeric NOT NULL, "idle_worker_shares" numeric NOT NULL, "cumulative_rewards" numeric NOT NULL, "pha_rate" numeric NOT NULL, "budget_per_block" numeric NOT NULL, "v_max" numeric NOT NULL, "treasury_ratio" numeric NOT NULL, "re" numeric NOT NULL, "k" numeric NOT NULL, "worker_count" integer NOT NULL, "idle_worker_count" integer NOT NULL, "budget_per_share" numeric NOT NULL, "delegator_count" integer NOT NULL, "withdrawal_dust_cleared" boolean, CONSTRAINT "PK_8b4db1150cf49bfd067e2572c74" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "base_pool_whitelist" ("id" character varying NOT NULL, "create_time" TIMESTAMP WITH TIME ZONE NOT NULL, "account_id" character varying, "base_pool_id" character varying, CONSTRAINT "PK_1a86621574257deb7a2b7b4d7d7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_57aaf3859a02333f595bd5bd22" ON "base_pool_whitelist" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_c9fe1c8727e265ebcdb30019b6" ON "base_pool_whitelist" ("base_pool_id", "create_time") `)
        await db.query(`CREATE TABLE "nft" ("id" character varying NOT NULL, "cid" integer NOT NULL, "nft_id" integer NOT NULL, "mint_time" TIMESTAMP WITH TIME ZONE, "owner_id" character varying, CONSTRAINT "PK_8f46897c58e23b0e7bf6c8e56b0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_83cfd3a290ed70c660f8c9dfe2" ON "nft" ("owner_id") `)
        await db.query(`CREATE UNIQUE INDEX "IDX_1491e9421517dacf9493a21e2a" ON "nft" ("cid", "nft_id") `)
        await db.query(`CREATE TABLE "delegation" ("id" character varying NOT NULL, "value" numeric NOT NULL, "cost" numeric NOT NULL, "shares" numeric NOT NULL, "withdrawing_value" numeric NOT NULL, "withdrawing_shares" numeric NOT NULL, "withdrawal_start_time" TIMESTAMP WITH TIME ZONE, "account_id" character varying, "base_pool_id" character varying, "delegation_nft_id" character varying, "withdrawal_nft_id" character varying, CONSTRAINT "REL_2d6f29d59b2d5cd7e3034ab857" UNIQUE ("delegation_nft_id"), CONSTRAINT "REL_f7f610da28f4e55602c9def52a" UNIQUE ("withdrawal_nft_id"), CONSTRAINT "PK_a2cb6c9b942d68b109131beab44" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_be5a5e334e4fb53a0cab3b0125" ON "delegation" ("account_id") `)
        await db.query(`CREATE UNIQUE INDEX "IDX_2d6f29d59b2d5cd7e3034ab857" ON "delegation" ("delegation_nft_id") `)
        await db.query(`CREATE UNIQUE INDEX "IDX_f7f610da28f4e55602c9def52a" ON "delegation" ("withdrawal_nft_id") `)
        await db.query(`CREATE UNIQUE INDEX "IDX_4e416c213dddda196b1b42be7e" ON "delegation" ("base_pool_id", "account_id") `)
        await db.query(`CREATE TABLE "base_pool" ("id" character varying NOT NULL, "pid" numeric NOT NULL, "cid" integer NOT NULL, "kind" character varying(9) NOT NULL, "commission" numeric NOT NULL, "apr_multiplier" numeric NOT NULL, "total_shares" numeric NOT NULL, "total_value" numeric NOT NULL, "share_price" numeric NOT NULL, "free_value" numeric NOT NULL, "releasing_value" numeric NOT NULL, "withdrawing_value" numeric NOT NULL, "withdrawing_shares" numeric NOT NULL, "delegator_count" integer NOT NULL, "whitelist_enabled" boolean NOT NULL, "cumulative_owner_rewards" numeric NOT NULL, "owner_id" character varying, "account_id" character varying, CONSTRAINT "REL_b17f3b9349da680afa1e2e9805" UNIQUE ("account_id"), CONSTRAINT "PK_eddfb05533fbdd025660778c6a2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_920be3ebc7213397ec0cb30fd8" ON "base_pool" ("pid") `)
        await db.query(`CREATE INDEX "IDX_e20be4204009ad2ad1d17a125d" ON "base_pool" ("owner_id") `)
        await db.query(`CREATE UNIQUE INDEX "IDX_b17f3b9349da680afa1e2e9805" ON "base_pool" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_e27b78a0b9c8bb7cf557583c0f" ON "base_pool" ("kind") `)
        await db.query(`CREATE INDEX "IDX_d71a9ba0c1c3f3340dd87064b4" ON "base_pool" ("apr_multiplier") `)
        await db.query(`CREATE INDEX "IDX_3ddfb0de970509e9b4a4124d81" ON "base_pool" ("total_value") `)
        await db.query(`CREATE INDEX "IDX_d10ad72d6b96462451991fb419" ON "base_pool" ("whitelist_enabled") `)
        await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, "identity_display" text, "identity_level" character varying(10), "identity_judgements" character varying(10) array, "stake_pool_value" numeric NOT NULL, "stake_pool_nft_count" integer NOT NULL, "stake_pool_avg_apr_multiplier" numeric NOT NULL, "vault_value" numeric NOT NULL, "vault_nft_count" integer NOT NULL, "vault_avg_apr_multiplier" numeric NOT NULL, "cumulative_stake_pool_owner_rewards" numeric NOT NULL, "cumulative_vault_owner_rewards" numeric NOT NULL, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5db95abd660552bdaa77e1b552" ON "account" ("identity_display") `)
        await db.query(`CREATE TABLE "vault" ("id" character varying NOT NULL, "last_share_price_checkpoint" numeric NOT NULL, "claimable_owner_shares" numeric NOT NULL, "base_pool_id" character varying, CONSTRAINT "REL_79f07f6ce7cca2f1ebfc2c0b11" UNIQUE ("base_pool_id"), CONSTRAINT "PK_dd0898234c77f9d97585171ac59" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "IDX_79f07f6ce7cca2f1ebfc2c0b11" ON "vault" ("base_pool_id") `)
        await db.query(`CREATE TABLE "worker" ("id" character varying NOT NULL, "confidence_level" integer NOT NULL, "initial_score" integer, "stake_pool_id" character varying, CONSTRAINT "PK_dc8175fa0e34ce7a39e4ec73b94" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_81caea9d964ee3c0338fd44db4" ON "worker" ("stake_pool_id") `)
        await db.query(`CREATE TABLE "stake_pool" ("id" character varying NOT NULL, "capacity" numeric, "delegable" numeric, "owner_reward" numeric NOT NULL, "worker_count" integer NOT NULL, "idle_worker_count" integer NOT NULL, "idle_worker_shares" numeric NOT NULL, "base_pool_id" character varying, CONSTRAINT "REL_663952452d6814016e857b710b" UNIQUE ("base_pool_id"), CONSTRAINT "PK_646d137a2979aa231fa880711f3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "IDX_663952452d6814016e857b710b" ON "stake_pool" ("base_pool_id") `)
        await db.query(`CREATE TABLE "session" ("id" character varying NOT NULL, "stake" numeric NOT NULL, "state" character varying(18) NOT NULL, "v" numeric NOT NULL, "ve" numeric NOT NULL, "p_init" integer NOT NULL, "p_instant" integer NOT NULL, "total_reward" numeric NOT NULL, "cooling_down_start_time" TIMESTAMP WITH TIME ZONE, "shares" numeric NOT NULL, "worker_id" character varying, CONSTRAINT "REL_30db46e58a0ae3fbc408179de8" UNIQUE ("worker_id"), CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "IDX_30db46e58a0ae3fbc408179de8" ON "session" ("worker_id") `)
        await db.query(`CREATE TABLE "account_snapshot" ("id" character varying NOT NULL, "updated_time" TIMESTAMP WITH TIME ZONE NOT NULL, "account" text NOT NULL, "delegation_value" numeric NOT NULL, "cumulative_stake_pool_owner_rewards" numeric NOT NULL, "cumulative_vault_owner_rewards" numeric NOT NULL, CONSTRAINT "PK_3296654a614882b571b225c84e3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "IDX_114923489e01e385119439b38a" ON "account_snapshot" ("account", "updated_time") `)
        await db.query(`CREATE TABLE "base_pool_snapshot" ("id" character varying NOT NULL, "updated_time" TIMESTAMP WITH TIME ZONE NOT NULL, "base_pool" text NOT NULL, "commission" numeric NOT NULL, "apr" numeric NOT NULL, "total_shares" numeric NOT NULL, "total_value" numeric NOT NULL, "share_price" numeric NOT NULL, "free_value" numeric NOT NULL, "releasing_value" numeric NOT NULL, "withdrawing_value" numeric NOT NULL, "withdrawing_shares" numeric NOT NULL, "delegator_count" integer NOT NULL, "worker_count" integer, "idle_worker_count" integer, "stake_pool_count" integer, "cumulative_owner_rewards" numeric NOT NULL, CONSTRAINT "PK_7adc035ceca68381a1613757d2a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "IDX_de91ab969c75330a623600b6de" ON "base_pool_snapshot" ("base_pool", "updated_time") `)
        await db.query(`CREATE TABLE "global_state_snapshot" ("id" character varying NOT NULL, "height" integer NOT NULL, "updated_time" TIMESTAMP WITH TIME ZONE NOT NULL, "total_value" numeric NOT NULL, "average_block_time" integer NOT NULL, "average_apr" numeric NOT NULL, "idle_worker_shares" numeric NOT NULL, "cumulative_rewards" numeric NOT NULL, "budget_per_block" numeric NOT NULL, "worker_count" integer NOT NULL, "idle_worker_count" integer NOT NULL, "budget_per_share" numeric NOT NULL, "delegator_count" integer NOT NULL, CONSTRAINT "PK_f168dfb48948e182df276f30021" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_b791e12fdeb4c189a73b160a64" ON "global_state_snapshot" ("height") `)
        await db.query(`CREATE INDEX "IDX_51f536d736eee486c1a2acca1a" ON "global_state_snapshot" ("updated_time") `)
        await db.query(`CREATE TABLE "delegation_snapshot" ("id" character varying NOT NULL, "updated_time" TIMESTAMP WITH TIME ZONE NOT NULL, "delegation" text NOT NULL, "cost" numeric NOT NULL, "value" numeric NOT NULL, CONSTRAINT "PK_335066227038f09d171baca0bb9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "IDX_6bd56f9ee58c8be8ce385a4c08" ON "delegation_snapshot" ("delegation", "updated_time") `)
        await db.query(`CREATE TABLE "worker_snapshot" ("id" character varying NOT NULL, "updated_time" TIMESTAMP WITH TIME ZONE NOT NULL, "worker" text NOT NULL, "stake_pool" text NOT NULL, "session" text NOT NULL, "confidence_level" integer NOT NULL, "initial_score" integer, "stake" numeric NOT NULL, "state" character varying(18) NOT NULL, "v" numeric NOT NULL, "ve" numeric NOT NULL, "p_init" integer NOT NULL, "p_instant" integer NOT NULL, "total_reward" numeric NOT NULL, CONSTRAINT "PK_5140a438c3891406b7420770cb9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "IDX_99df4d67cde03dadbfa7bc5c97" ON "worker_snapshot" ("worker", "updated_time") `)
        await db.query(`ALTER TABLE "base_pool_whitelist" ADD CONSTRAINT "FK_57aaf3859a02333f595bd5bd224" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "base_pool_whitelist" ADD CONSTRAINT "FK_993eea06189ccb1817da97adaba" FOREIGN KEY ("base_pool_id") REFERENCES "base_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_83cfd3a290ed70c660f8c9dfe2c" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation" ADD CONSTRAINT "FK_be5a5e334e4fb53a0cab3b01254" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation" ADD CONSTRAINT "FK_4b95628b3ff2b93f23b1f59ae44" FOREIGN KEY ("base_pool_id") REFERENCES "base_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation" ADD CONSTRAINT "FK_2d6f29d59b2d5cd7e3034ab8574" FOREIGN KEY ("delegation_nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation" ADD CONSTRAINT "FK_f7f610da28f4e55602c9def52a5" FOREIGN KEY ("withdrawal_nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "base_pool" ADD CONSTRAINT "FK_e20be4204009ad2ad1d17a125de" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "base_pool" ADD CONSTRAINT "FK_b17f3b9349da680afa1e2e98055" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "vault" ADD CONSTRAINT "FK_79f07f6ce7cca2f1ebfc2c0b117" FOREIGN KEY ("base_pool_id") REFERENCES "base_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "worker" ADD CONSTRAINT "FK_81caea9d964ee3c0338fd44db4a" FOREIGN KEY ("stake_pool_id") REFERENCES "stake_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stake_pool" ADD CONSTRAINT "FK_663952452d6814016e857b710b4" FOREIGN KEY ("base_pool_id") REFERENCES "base_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_30db46e58a0ae3fbc408179de88" FOREIGN KEY ("worker_id") REFERENCES "worker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "global_state"`)
        await db.query(`DROP TABLE "base_pool_whitelist"`)
        await db.query(`DROP INDEX "public"."IDX_57aaf3859a02333f595bd5bd22"`)
        await db.query(`DROP INDEX "public"."IDX_c9fe1c8727e265ebcdb30019b6"`)
        await db.query(`DROP TABLE "nft"`)
        await db.query(`DROP INDEX "public"."IDX_83cfd3a290ed70c660f8c9dfe2"`)
        await db.query(`DROP INDEX "public"."IDX_1491e9421517dacf9493a21e2a"`)
        await db.query(`DROP TABLE "delegation"`)
        await db.query(`DROP INDEX "public"."IDX_be5a5e334e4fb53a0cab3b0125"`)
        await db.query(`DROP INDEX "public"."IDX_2d6f29d59b2d5cd7e3034ab857"`)
        await db.query(`DROP INDEX "public"."IDX_f7f610da28f4e55602c9def52a"`)
        await db.query(`DROP INDEX "public"."IDX_4e416c213dddda196b1b42be7e"`)
        await db.query(`DROP TABLE "base_pool"`)
        await db.query(`DROP INDEX "public"."IDX_920be3ebc7213397ec0cb30fd8"`)
        await db.query(`DROP INDEX "public"."IDX_e20be4204009ad2ad1d17a125d"`)
        await db.query(`DROP INDEX "public"."IDX_b17f3b9349da680afa1e2e9805"`)
        await db.query(`DROP INDEX "public"."IDX_e27b78a0b9c8bb7cf557583c0f"`)
        await db.query(`DROP INDEX "public"."IDX_d71a9ba0c1c3f3340dd87064b4"`)
        await db.query(`DROP INDEX "public"."IDX_3ddfb0de970509e9b4a4124d81"`)
        await db.query(`DROP INDEX "public"."IDX_d10ad72d6b96462451991fb419"`)
        await db.query(`DROP TABLE "account"`)
        await db.query(`DROP INDEX "public"."IDX_5db95abd660552bdaa77e1b552"`)
        await db.query(`DROP TABLE "vault"`)
        await db.query(`DROP INDEX "public"."IDX_79f07f6ce7cca2f1ebfc2c0b11"`)
        await db.query(`DROP TABLE "worker"`)
        await db.query(`DROP INDEX "public"."IDX_81caea9d964ee3c0338fd44db4"`)
        await db.query(`DROP TABLE "stake_pool"`)
        await db.query(`DROP INDEX "public"."IDX_663952452d6814016e857b710b"`)
        await db.query(`DROP TABLE "session"`)
        await db.query(`DROP INDEX "public"."IDX_30db46e58a0ae3fbc408179de8"`)
        await db.query(`DROP TABLE "account_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_114923489e01e385119439b38a"`)
        await db.query(`DROP TABLE "base_pool_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_de91ab969c75330a623600b6de"`)
        await db.query(`DROP TABLE "global_state_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_b791e12fdeb4c189a73b160a64"`)
        await db.query(`DROP INDEX "public"."IDX_51f536d736eee486c1a2acca1a"`)
        await db.query(`DROP TABLE "delegation_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_6bd56f9ee58c8be8ce385a4c08"`)
        await db.query(`DROP TABLE "worker_snapshot"`)
        await db.query(`DROP INDEX "public"."IDX_99df4d67cde03dadbfa7bc5c97"`)
        await db.query(`ALTER TABLE "base_pool_whitelist" DROP CONSTRAINT "FK_57aaf3859a02333f595bd5bd224"`)
        await db.query(`ALTER TABLE "base_pool_whitelist" DROP CONSTRAINT "FK_993eea06189ccb1817da97adaba"`)
        await db.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_83cfd3a290ed70c660f8c9dfe2c"`)
        await db.query(`ALTER TABLE "delegation" DROP CONSTRAINT "FK_be5a5e334e4fb53a0cab3b01254"`)
        await db.query(`ALTER TABLE "delegation" DROP CONSTRAINT "FK_4b95628b3ff2b93f23b1f59ae44"`)
        await db.query(`ALTER TABLE "delegation" DROP CONSTRAINT "FK_2d6f29d59b2d5cd7e3034ab8574"`)
        await db.query(`ALTER TABLE "delegation" DROP CONSTRAINT "FK_f7f610da28f4e55602c9def52a5"`)
        await db.query(`ALTER TABLE "base_pool" DROP CONSTRAINT "FK_e20be4204009ad2ad1d17a125de"`)
        await db.query(`ALTER TABLE "base_pool" DROP CONSTRAINT "FK_b17f3b9349da680afa1e2e98055"`)
        await db.query(`ALTER TABLE "vault" DROP CONSTRAINT "FK_79f07f6ce7cca2f1ebfc2c0b117"`)
        await db.query(`ALTER TABLE "worker" DROP CONSTRAINT "FK_81caea9d964ee3c0338fd44db4a"`)
        await db.query(`ALTER TABLE "stake_pool" DROP CONSTRAINT "FK_663952452d6814016e857b710b4"`)
        await db.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_30db46e58a0ae3fbc408179de88"`)
    }
}
