version: "3"

services:
  db:
    container_name: phala_stake_pool_v2_subsquid_db
    image: postgres:14
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: squid
    ports:
      - "${DB_PORT}:5432"
    command: ["postgres", "-c", "log_statement=all"]
#    volumes:
#      - ./data/db:/var/lib/postgresql/data

